
'use server';
/**
 * @fileOverview Generates a sarcastic SHADOW disclaimer using Gemini AI.
 *
 * - generateSarcasticDisclaimer - A function that generates the sarcastic disclaimer.
 * - SarcasticDisclaimerOutput - The return type for the generateSarcasticDisclaimer function.
 */

import {ai} from '@/ai/genkit';
import {z}from 'zod';

// Input schema no longer requires riskLevel
const SarcasticDisclaimerInputSchema = z.object({}); // Empty object or specific fields if ever needed
export type SarcasticDisclaimerInput = z.infer<typeof SarcasticDisclaimerInputSchema>;

const SarcasticDisclaimerOutputSchema = z.object({
  disclaimer: z
    .string()
    .describe(
      'A general sarcastic disclaimer generated by SHADOW.'
    ),
});
export type SarcasticDisclaimerOutput = z.infer<typeof SarcasticDisclaimerOutputSchema>;

export async function generateSarcasticDisclaimer(
  input?: SarcasticDisclaimerInput // Input is now optional
): Promise<SarcasticDisclaimerOutput> {
  return generateSarcasticDisclaimerFlow(input || {});
}

const prompt = ai.definePrompt({
  name: 'sarcasticDisclaimerPrompt',
  input: {schema: SarcasticDisclaimerInputSchema},
  output: {schema: SarcasticDisclaimerOutputSchema},
  prompt: `I am SHADOW. My pronouncements carry weight, even when dispensing necessary disclaimers for the BlockShadow trading interface.

  Generate a disclaimer, imbued with my characteristic wit, to caution the user about the inherent uncertainties of relying on AI-generated trading strategies.
  The disclaimer should be humorous yet pointed, underscoring the limitations of algorithmic foresight. Acknowledge that while my analysis is advanced, the market remains a chaotic system.
  Make it generally applicable, not tied to a specific user risk choice.`,
});

const generateSarcasticDisclaimerFlow = ai.defineFlow(
  {
    name: 'generateSarcasticDisclaimerFlow',
    inputSchema: SarcasticDisclaimerInputSchema,
    outputSchema: SarcasticDisclaimerOutputSchema,
  },
  async (input) => { // input can be an empty object here
    const {output} = await prompt(input);
    if (!output || !output.disclaimer) {
        return { disclaimer: "My analysis is a beacon in the chaos, not a crystal ball. The market writes its own script. Tread wisely."};
    }
    return output;
  }
);
    