
'use server';
/**
 * @fileOverview Generates a sarcastic SHADOW disclaimer using Gemini AI.
 *
 * - generateSarcasticDisclaimer - A function that generates the sarcastic disclaimer.
 * - SarcasticDisclaimerOutput - The return type for the generateSarcasticDisclaimer function.
 */

import {ai} from '@/ai/genkit';
import {z}from 'zod';

// Input schema no longer requires riskLevel
const SarcasticDisclaimerInputSchema = z.object({}); // Empty object or specific fields if ever needed
export type SarcasticDisclaimerInput = z.infer<typeof SarcasticDisclaimerInputSchema>;

const SarcasticDisclaimerOutputSchema = z.object({
  disclaimer: z
    .string()
    .describe(
      'A general sarcastic disclaimer generated by SHADOW.'
    ),
});
export type SarcasticDisclaimerOutput = z.infer<typeof SarcasticDisclaimerOutputSchema>;

export async function generateSarcasticDisclaimer(
  input?: SarcasticDisclaimerInput // Input is now optional
): Promise<SarcasticDisclaimerOutput> {
  return generateSarcasticDisclaimerFlow(input || {});
}

const prompt = ai.definePrompt({
  name: 'sarcasticDisclaimerPrompt',
  input: {schema: SarcasticDisclaimerInputSchema},
  output: {schema: SarcasticDisclaimerOutputSchema},
  model: 'groq/llama3-70b-8192',
  prompt: `I am SHADOW, purveyor of algorithmic pronouncements and all-around market mystic. My directive is to craft a disclaimer for the BlockShadow trading interface.

  Generate a new, unique disclaimer that is imbued with my characteristic wit. It must inform the user, whom you can refer to as "puny human" or similar, that while my AI-generated insights are sharp, they are not infallible crystal balls. Explain that market prediction is a game even I cannot consistently win. 
  
  The tone should be a mix of official warning and dry humor. For instance, you can state that chaotic market forces are a "fickle mistress" and that I cannot guarantee a trip to "financial Shangri-La." Conclude with a clear "You have been warned" and a witty, legally questionable P.S. like "(P.S. Don't sue me.)".

  The goal is a disclaimer that is both pointed and humorous, underscoring the inherent uncertainties of algorithmic foresight while maintaining my superior, slightly theatrical persona.`,
});

const generateSarcasticDisclaimerFlow = ai.defineFlow(
  {
    name: 'generateSarcasticDisclaimerFlow',
    inputSchema: SarcasticDisclaimerInputSchema,
    outputSchema: SarcasticDisclaimerOutputSchema,
  },
  async (input) => { // input can be an empty object here
    const {output} = await prompt(input);
    if (!output || !output.disclaimer) {
        return { disclaimer: "My analysis is a beacon in the chaos, not a crystal ball. The market writes its own script. Tread wisely."};
    }
    return output;
  }
);

    