
-- This script is for setting up the initial database schema in a PostgreSQL database (like Neon).
-- You can run this script directly in your database provider's SQL editor.

-- Users Table
-- Stores user profile information, including airdrop registration data.
CREATE TABLE IF NOT EXISTS "users" (
    "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "username" TEXT UNIQUE NOT NULL,
    "status" TEXT,
    "shadowId" TEXT UNIQUE,
    "weeklyPoints" INTEGER NOT NULL DEFAULT 0,
    "airdropPoints" INTEGER NOT NULL DEFAULT 0,
    "wallet_address" TEXT UNIQUE,
    "wallet_type" TEXT,
    "email" TEXT,
    "phone" TEXT,
    "x_handle" TEXT,
    "telegram_handle" TEXT,
    "youtube_handle" TEXT,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Badges Table
-- Stores the different types of badges users can earn.
CREATE TABLE IF NOT EXISTS "badges" (
    "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- UserBadges Join Table (_UserBadges)
-- Manages the many-to-many relationship between users and badges.
-- Follows Prisma's convention for relation tables.
CREATE TABLE IF NOT EXISTS "_UserBadges" (
    "A" UUID NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
    "B" UUID NOT NULL REFERENCES "badges"("id") ON DELETE CASCADE,
    PRIMARY KEY ("A", "B")
);

-- Console Insights Table
-- Stores analytical insights generated by users.
CREATE TABLE IF NOT EXISTS "console_insights" (
    "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "userId" UUID NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
    "content" TEXT NOT NULL,
    "timestamp" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Signals Table
-- Stores the history of trading signals generated by users.
CREATE TABLE IF NOT EXISTS "signals" (
    "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "userId" UUID NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
    "signalType" TEXT NOT NULL,
    "symbol" TEXT NOT NULL,
    "price" NUMERIC NOT NULL,
    "timestamp" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for foreign keys to improve query performance.
CREATE INDEX IF NOT EXISTS "idx_UserBadges_A" ON "_UserBadges"("A");
CREATE INDEX IF NOT EXISTS "idx_UserBadges_B" ON "_UserBadges"("B");
CREATE INDEX IF NOT EXISTS "idx_console_insights_userId" ON "console_insights"("userId");
CREATE INDEX IF NOT EXISTS "idx_signals_userId" ON "signals"("userId");

-- Create an index on weeklyPoints for leaderboard performance.
CREATE INDEX IF NOT EXISTS "idx_users_weeklyPoints" ON "users"("weeklyPoints" DESC);

-- Create an index on wallet_address for faster lookups.
CREATE INDEX IF NOT EXISTS "idx_users_wallet_address" ON "users"("wallet_address");
